export const currSymbolData = [
  {
    currencyCode: "AED",
    name: "UAE Dirham",
    country: "United Arab Emirates",
    countryCode: "AE",
  },
  {
    currencyCode: "AFN",
    name: "Afghan Afghani",
    country: "Afghanistan",
    countryCode: "AF",
  },
  {
    currencyCode: "ALL",
    name: "Albanian Lek",
    country: "Albania",
    countryCode: "AL",
  },
  {
    currencyCode: "AMD",
    name: "Armenian Dram",
    country: "Armenia",
    countryCode: "AM",
  },
  {
    currencyCode: "ANG",
    name: "Netherlands Antillian Guilder",
    country: "Netherlands Antilles",
    countryCode: "AN",
  },
  {
    currencyCode: "AOA",
    name: "Angolan Kwanza",
    country: "Angola",
    countryCode: "AO",
  },
  {
    currencyCode: "ARS",
    name: "Argentine Peso",
    country: "Argentina",
    countryCode: "AR",
  },
  {
    currencyCode: "AUD",
    name: "Australian Dollar",
    country: "Australia",
    countryCode: "AU",
  },
  {
    currencyCode: "AWG",
    name: "Aruban Florin",
    country: "Aruba",
    countryCode: "AW",
  },
  {
    currencyCode: "AZN",
    name: "Azerbaijani Manat",
    country: "Azerbaijan",
    countryCode: "AZ",
  },
  {
    currencyCode: "BAM",
    name: "Bosnia and Herzegovina Mark",
    country: "Bosnia and Herzegovina",
    countryCode: "BA",
  },
  {
    currencyCode: "BBD",
    name: "Barbados Dollar",
    country: "Barbados",
    countryCode: "BB",
  },
  {
    currencyCode: "BDT",
    name: "Bangladeshi Taka",
    country: "Bangladesh",
    countryCode: "BD",
  },
  {
    currencyCode: "BGN",
    name: "Bulgarian Lev",
    country: "Bulgaria",
    countryCode: "BG",
  },
  {
    currencyCode: "BHD",
    name: "Bahraini Dinar",
    country: "Bahrain",
    countryCode: "BH",
  },
  {
    currencyCode: "BIF",
    name: "Burundian Franc",
    country: "Burundi",
    countryCode: "BI",
  },
  {
    currencyCode: "BMD",
    name: "Bermudian Dollar",
    country: "Bermuda",
    countryCode: "BM",
  },
  {
    currencyCode: "BND",
    name: "Brunei Dollar",
    country: "Brunei Darussalam",
    countryCode: "BN",
  },
  {
    currencyCode: "BOB",
    name: "Bolivian Boliviano",
    country: "Bolivia",
    countryCode: "BO",
  },
  {
    currencyCode: "BRL",
    name: "Brazilian Real",
    country: "Brazil",
    countryCode: "BR",
  },
  {
    currencyCode: "BSD",
    name: "Bahamian Dollar",
    country: "Bahamas",
    countryCode: "BS",
  },
  {
    currencyCode: "BTN",
    name: "Bhutanese Ngultrum",
    country: "Bhutan",
    countryCode: "BT",
  },
  {
    currencyCode: "BWP",
    name: "Botswana Pula",
    country: "Botswana",
    countryCode: "BW",
  },
  {
    currencyCode: "BYN",
    name: "Belarusian Ruble",
    country: "Belarus",
    countryCode: "BY",
  },
  {
    currencyCode: "BZD",
    name: "Belize Dollar",
    country: "Belize",
    countryCode: "BZ",
  },
  {
    currencyCode: "CAD",
    name: "Canadian Dollar",
    country: "Canada",
    countryCode: "CA",
  },
  {
    currencyCode: "CDF",
    name: "Congolese Franc",
    country: "Democratic Republic of the Congo",
    countryCode: "CD",
  },
  {
    currencyCode: "CHF",
    name: "Swiss Franc",
    country: "Switzerland",
    countryCode: "CH",
  },
  {
    currencyCode: "CLP",
    name: "Chilean Peso",
    country: "Chile",
    countryCode: "CL",
  },
  {
    currencyCode: "CNY",
    name: "Chinese Renminbi",
    country: "China",
    countryCode: "CN",
  },
  {
    currencyCode: "COP",
    name: "Colombian Peso",
    country: "Colombia",
    countryCode: "CO",
  },
  {
    currencyCode: "CRC",
    name: "Costa Rican Colon",
    country: "Costa Rica",
    countryCode: "CR",
  },
  {
    currencyCode: "CUP",
    name: "Cuban Peso",
    country: "Cuba",
    countryCode: "CU",
  },
  {
    currencyCode: "CVE",
    name: "Cape Verdean Escudo",
    country: "Cape Verde",
    countryCode: "CV",
  },
  {
    currencyCode: "CZK",
    name: "Czech Koruna",
    country: "Czech Republic",
    countryCode: "CZ",
  },
  {
    currencyCode: "DJF",
    name: "Djiboutian Franc",
    country: "Djibouti",
    countryCode: "DJ",
  },
  {
    currencyCode: "DKK",
    name: "Danish Krone",
    country: "Denmark",
    countryCode: "DK",
  },
  {
    currencyCode: "DOP",
    name: "Dominican Peso",
    country: "Dominican Republic",
    countryCode: "DO",
  },
  {
    currencyCode: "DZD",
    name: "Algerian Dinar",
    country: "Algeria",
    countryCode: "DZ",
  },
  {
    currencyCode: "EGP",
    name: "Egyptian Pound",
    country: "Egypt",
    countryCode: "EG",
  },
  {
    currencyCode: "ERN",
    name: "Eritrean Nakfa",
    country: "Eritrea",
    countryCode: "ER",
  },
  {
    currencyCode: "ETB",
    name: "Ethiopian Birr",
    country: "Ethiopia",
    countryCode: "ET",
  },
  {
    currencyCode: "EUR",
    name: "Euro",
    country: "European Union",
    countryCode: "eu",
  },
  {
    currencyCode: "FJD",
    name: "Fiji Dollar",
    country: "Fiji",
    countryCode: "FJ",
  },
  {
    currencyCode: "FKP",
    name: "Falkland Islands Pound",
    country: "Falkland Islands",
    countryCode: "FK",
  },
  {
    currencyCode: "FOK",
    name: "Faroese Króna",
    country: "Faroe Islands",
    countryCode: "FO",
  },
  {
    currencyCode: "GBP",
    name: "Pound Sterling",
    country: "United Kingdom",
    countryCode: "GB",
  },
  {
    currencyCode: "GEL",
    name: "Georgian Lari",
    country: "Georgia",
    countryCode: "GE",
  },
  {
    currencyCode: "GGP",
    name: "Guernsey Pound",
    country: "Guernsey",
    countryCode: "GG",
  },
  {
    currencyCode: "GHS",
    name: "Ghanaian Cedi",
    country: "Ghana",
    countryCode: "GH",
  },
  {
    currencyCode: "GIP",
    name: "Gibraltar Pound",
    country: "Gibraltar",
    countryCode: "GI",
  },
  {
    currencyCode: "GMD",
    name: "Gambian Dalasi",
    country: "The Gambia",
    countryCode: "GM",
  },
  {
    currencyCode: "GNF",
    name: "Guinean Franc",
    country: "Guinea",
    countryCode: "GN",
  },
  {
    currencyCode: "GTQ",
    name: "Guatemalan Quetzal",
    country: "Guatemala",
    countryCode: "GT",
  },
  {
    currencyCode: "GYD",
    name: "Guyanese Dollar",
    country: "Guyana",
    countryCode: "GY",
  },
  {
    currencyCode: "HKD",
    name: "Hong Kong Dollar",
    country: "Hong Kong",
    countryCode: "HK",
  },
  {
    currencyCode: "HNL",
    name: "Honduran Lempira",
    country: "Honduras",
    countryCode: "HN",
  },
  {
    currencyCode: "HRK",
    name: "Croatian Kuna",
    country: "Croatia",
    countryCode: "HR",
  },
  {
    currencyCode: "HTG",
    name: "Haitian Gourde",
    country: "Haiti",
    countryCode: "HT",
  },
  {
    currencyCode: "HUF",
    name: "Hungarian Forint",
    country: "Hungary",
    countryCode: "HU",
  },
  {
    currencyCode: "IDR",
    name: "Indonesian Rupiah",
    country: "Indonesia",
    countryCode: "ID",
  },
  {
    currencyCode: "ILS",
    name: "Israeli New Shekel",
    country: "Israel",
    countryCode: "IL",
  },
  {
    currencyCode: "IMP",
    name: "Manx Pound",
    country: "Isle of Man",
    countryCode: "IM",
  },
  {
    currencyCode: "INR",
    name: "Indian Rupee",
    country: "India",
    countryCode: "IN",
  },
  {
    currencyCode: "IQD",
    name: "Iraqi Dinar",
    country: "Iraq",
    countryCode: "IQ",
  },
  {
    currencyCode: "IRR",
    name: "Iranian Rial",
    country: "Iran",
    countryCode: "IR",
  },
  {
    currencyCode: "ISK",
    name: "Icelandic Króna",
    country: "Iceland",
    countryCode: "IS",
  },
  {
    currencyCode: "JEP",
    name: "Jersey Pound",
    country: "Jersey",
    countryCode: "JE",
  },
  {
    currencyCode: "JMD",
    name: "Jamaican Dollar",
    country: "Jamaica",
    countryCode: "JM",
  },
  {
    currencyCode: "JOD",
    name: "Jordanian Dinar",
    country: "Jordan",
    countryCode: "JO",
  },
  {
    currencyCode: "JPY",
    name: "Japanese Yen",
    country: "Japan",
    countryCode: "JP",
  },
  {
    currencyCode: "KES",
    name: "Kenyan Shilling",
    country: "Kenya",
    countryCode: "KE",
  },
  {
    currencyCode: "KGS",
    name: "Kyrgyzstani Som",
    country: "Kyrgyzstan",
    countryCode: "KG",
  },
  {
    currencyCode: "KHR",
    name: "Cambodian Riel",
    country: "Cambodia",
    countryCode: "KH",
  },
  {
    currencyCode: "KID",
    name: "Kiribati Dollar",
    country: "Kiribati",
    countryCode: "KI",
  },
  {
    currencyCode: "KMF",
    name: "Comorian Franc",
    country: "Comoros",
    countryCode: "KM",
  },
  {
    currencyCode: "KRW",
    name: "South Korean Won",
    country: "South Korea",
    countryCode: "KR",
  },
  {
    currencyCode: "KWD",
    name: "Kuwaiti Dinar",
    country: "Kuwait",
    countryCode: "KW",
  },
  {
    currencyCode: "KYD",
    name: "Cayman Islands Dollar",
    country: "Cayman Islands",
    countryCode: "KY",
  },
  {
    currencyCode: "KZT",
    name: "Kazakhstani Tenge",
    country: "Kazakhstan",
    countryCode: "KZ",
  },
  {
    currencyCode: "LAK",
    name: "Lao Kip",
    country: "Laos",
    countryCode: "la",
  },
  {
    currencyCode: "LBP",
    name: "Lebanese Pound",
    country: "Lebanon",
    countryCode: "LB",
  },
  {
    currencyCode: "LKR",
    name: "Sri Lanka Rupee",
    country: "Sri Lanka",
    countryCode: "LK",
  },
  {
    currencyCode: "LRD",
    name: "Liberian Dollar",
    country: "Liberia",
    countryCode: "LR",
  },
  {
    currencyCode: "LSL",
    name: "Lesotho Loti",
    country: "Lesotho",
    countryCode: "LS",
  },
  {
    currencyCode: "LYD",
    name: "Libyan Dinar",
    country: "Libya",
    countryCode: "LY",
  },
  {
    currencyCode: "MAD",
    name: "Moroccan Dirham",
    country: "Morocco",
    countryCode: "MA",
  },
  {
    currencyCode: "MDL",
    name: "Moldovan Leu",
    country: "Moldova",
    countryCode: "MD",
  },
  {
    currencyCode: "MGA",
    name: "Malagasy Ariary",
    country: "Madagascar",
    countryCode: "MG",
  },
  {
    currencyCode: "MKD",
    name: "Macedonian Denar",
    country: "North Macedonia",
    countryCode: "mk",
  },
  {
    currencyCode: "MMK",
    name: "Burmese Kyat",
    country: "Myanmar",
    countryCode: "MM",
  },
  {
    currencyCode: "MNT",
    name: "Mongolian Tögrög",
    country: "Mongolia",
    countryCode: "MN",
  },
  {
    currencyCode: "MOP",
    name: "Macanese Pataca",
    country: "Macau",
    countryCode: "mi",
  },
  {
    currencyCode: "MRU",
    name: "Mauritanian Ouguiya",
    country: "Mauritania",
    countryCode: "MR",
  },
  {
    currencyCode: "MUR",
    name: "Mauritian Rupee",
    country: "Mauritius",
    countryCode: "MU",
  },
  {
    currencyCode: "MVR",
    name: "Maldivian Rufiyaa",
    country: "Maldives",
    countryCode: "MV",
  },
  {
    currencyCode: "MWK",
    name: "Malawian Kwacha",
    country: "Malawi",
    countryCode: "MW",
  },
  {
    currencyCode: "MXN",
    name: "Mexican Peso",
    country: "Mexico",
    countryCode: "MX",
  },
  {
    currencyCode: "MYR",
    name: "Malaysian Ringgit",
    country: "Malaysia",
    countryCode: "MY",
  },
  {
    currencyCode: "MZN",
    name: "Mozambican Metical",
    country: "Mozambique",
    countryCode: "MZ",
  },
  {
    currencyCode: "NAD",
    name: "Namibian Dollar",
    country: "Namibia",
    countryCode: "NA",
  },
  {
    currencyCode: "NGN",
    name: "Nigerian Naira",
    country: "Nigeria",
    countryCode: "NG",
  },
  {
    currencyCode: "NIO",
    name: "Nicaraguan Córdoba",
    country: "Nicaragua",
    countryCode: "NI",
  },
  {
    currencyCode: "NOK",
    name: "Norwegian Krone",
    country: "Norway",
    countryCode: "NO",
  },
  {
    currencyCode: "NPR",
    name: "Nepalese Rupee",
    country: "Nepal",
    countryCode: "NP",
  },
  {
    currencyCode: "NZD",
    name: "New Zealand Dollar",
    country: "New Zealand",
    countryCode: "NZ",
  },
  {
    currencyCode: "OMR",
    name: "Omani Rial",
    country: "Oman",
    countryCode: "OM",
  },
  {
    currencyCode: "PAB",
    name: "Panamanian Balboa",
    country: "Panama",
    countryCode: "PA",
  },
  {
    currencyCode: "PEN",
    name: "Peruvian Sol",
    country: "Peru",
    countryCode: "PE",
  },
  {
    currencyCode: "PGK",
    name: "Papua New Guinean Kina",
    country: "Papua New Guinea",
    countryCode: "PG",
  },
  {
    currencyCode: "PHP",
    name: "Philippine Peso",
    country: "Philippines",
    countryCode: "PH",
  },
  {
    currencyCode: "PKR",
    name: "Pakistani Rupee",
    country: "Pakistan",
    countryCode: "PK",
  },
  {
    currencyCode: "PLN",
    name: "Polish Złoty",
    country: "Poland",
    countryCode: "PL",
  },
  {
    currencyCode: "PYG",
    name: "Paraguayan Guaraní",
    country: "Paraguay",
    countryCode: "PY",
  },
  {
    currencyCode: "QAR",
    name: "Qatari Riyal",
    country: "Qatar",
    countryCode: "QA",
  },
  {
    currencyCode: "RON",
    name: "Romanian Leu",
    country: "Romania",
    countryCode: "RO",
  },
  {
    currencyCode: "RSD",
    name: "Serbian Dinar",
    country: "Serbia",
    countryCode: "RS",
  },
  {
    currencyCode: "RUB",
    name: "Russian Ruble",
    country: "Russia",
    countryCode: "RU",
  },
  {
    currencyCode: "RWF",
    name: "Rwandan Franc",
    country: "Rwanda",
    countryCode: "RW",
  },
  {
    currencyCode: "SAR",
    name: "Saudi Riyal",
    country: "Saudi Arabia",
    countryCode: "SA",
  },
  {
    currencyCode: "SBD",
    name: "Solomon Islands Dollar",
    country: "Solomon Islands",
    countryCode: "SB",
  },
  {
    currencyCode: "SCR",
    name: "Seychellois Rupee",
    country: "Seychelles",
    countryCode: "SC",
  },
  {
    currencyCode: "SDG",
    name: "Sudanese Pound",
    country: "Sudan",
    countryCode: "SD",
  },
  {
    currencyCode: "SEK",
    name: "Swedish Krona",
    country: "Sweden",
    countryCode: "SE",
  },
  {
    currencyCode: "SGD",
    name: "Singapore Dollar",
    country: "Singapore",
    countryCode: "SG",
  },
  {
    currencyCode: "SHP",
    name: "Saint Helena Pound",
    country: "Saint Helena",
    countryCode: "SH",
  },
  {
    currencyCode: "SLL",
    name: "Sierra Leonean Leone",
    country: "Sierra Leone",
    countryCode: "SL",
  },
  {
    currencyCode: "SOS",
    name: "Somali Shilling",
    country: "Somalia",
    countryCode: "SO",
  },
  {
    currencyCode: "SRD",
    name: "Surinamese Dollar",
    country: "Suriname",
    countryCode: "SR",
  },
  {
    currencyCode: "SSP",
    name: "South Sudanese Pound",
    country: "South Sudan",
    countryCode: "ss",
  },
  {
    currencyCode: "STN",
    name: "Sao Tome and Principe Dobra",
    country: "Sao Tome and Principe",
    countryCode: "ST",
  },
  {
    currencyCode: "SYP",
    name: "Syrian Pound",
    country: "Syria",
    countryCode: "SY",
  },
  {
    currencyCode: "SZL",
    name: "Eswatini Lilangeni",
    country: "Eswatini",
    countryCode: "SZ",
  },
  {
    currencyCode: "THB",
    name: "Thai Baht",
    country: "Thailand",
    countryCode: "TH",
  },
  {
    currencyCode: "TJS",
    name: "Tajikistani Somoni",
    country: "Tajikistan",
    countryCode: "TJ",
  },
  {
    currencyCode: "TMT",
    name: "Turkmenistan Manat",
    country: "Turkmenistan",
    countryCode: "TM",
  },
  {
    currencyCode: "TND",
    name: "Tunisian Dinar",
    country: "Tunisia",
    countryCode: "TN",
  },
  {
    currencyCode: "TOP",
    name: "Tongan Paʻanga",
    country: "Tonga",
    countryCode: "TO",
  },
  {
    currencyCode: "TRY",
    name: "Turkish Lira",
    country: "Turkey",
    countryCode: "TR",
  },
  {
    currencyCode: "TTD",
    name: "Trinidad and Tobago Dollar",
    country: "Trinidad and Tobago",
    countryCode: "TT",
  },
  {
    currencyCode: "TVD",
    name: "Tuvaluan Dollar",
    country: "Tuvalu",
    countryCode: "TV",
  },
  {
    currencyCode: "TWD",
    name: "New Taiwan Dollar",
    country: "Taiwan",
    countryCode: "TW",
  },
  {
    currencyCode: "TZS",
    name: "Tanzanian Shilling",
    country: "Tanzania",
    countryCode: "TZ",
  },
  {
    currencyCode: "UAH",
    name: "Ukrainian Hryvnia",
    country: "Ukraine",
    countryCode: "UA",
  },
  {
    currencyCode: "UGX",
    name: "Ugandan Shilling",
    country: "Uganda",
    countryCode: "UG",
  },
  {
    currencyCode: "USD",
    name: "United States Dollar",
    country: "United States",
    countryCode: "US",
  },
  {
    currencyCode: "UYU",
    name: "Uruguayan Peso",
    country: "Uruguay",
    countryCode: "UY",
  },
  {
    currencyCode: "UZS",
    name: "Uzbekistani So'm",
    country: "Uzbekistan",
    countryCode: "UZ",
  },
  {
    currencyCode: "VES",
    name: "Venezuelan Bolíconst Soberano",
    country: "Venezuela",
    countryCode: "VE",
  },
  {
    currencyCode: "VND",
    name: "Vietnamese Đồng",
    country: "Vietnam",
    countryCode: "vn",
  },
  {
    currencyCode: "VUV",
    name: "Vanuatu Vatu",
    country: "Vanuatu",
    countryCode: "VU",
  },
  {
    currencyCode: "WST",
    name: "Samoan Tālā",
    country: "Samoa",
    countryCode: "WS",
  },
  {
    currencyCode: "XOF",
    name: "West African CFA franc",
    country: "CFA",
    countryCode: "CF",
  },
  {
    currencyCode: "YER",
    name: "Yemeni Rial",
    country: "Yemen",
    countryCode: "YE",
  },
  {
    currencyCode: "ZAR",
    name: "South African Rand",
    country: "South Africa",
    countryCode: "ZA",
  },
  {
    currencyCode: "ZMW",
    name: "Zambian Kwacha",
    country: "Zambia",
    countryCode: "ZM",
  },
  {
    currencyCode: "ZWL",
    name: "Zimbabwean Dollar",
    country: "Zimbabwe",
    countryCode: "ZW",
  },
];
